spring:
  main:
    banner-mode: "off"
  application:
    name: database-migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/andreicoteata
    password:
    username: andreicoteata
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8081
database:
  ssl-config:
  host: localhost
  name: andreicoteata
  port: 5433
  username: andreicoteata
  password: